# fly.toml app configuration file generated for ppkolonie on 2023-08-15T10:55:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ppkolonie"
primary_region = "waw"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
